#!/usr/bin/env python3
"""Merge S2 string keys into app_en.arb and mirror to app_es.arb (English placeholders)."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
EN_PATH = ROOT / "lib/l10n/app_en.arb"
ES_PATH = ROOT / "lib/l10n/app_es.arb"

# Keys added in S2 — common first, then feature-specific.
S2_STRINGS: dict[str, str] = {
    # Common actions & labels
    "commonCancel": "Cancel",
    "commonSave": "Save",
    "commonDelete": "Delete",
    "commonRetry": "Retry",
    "commonClose": "Close",
    "commonArchive": "Archive",
    "commonMerge": "Merge",
    "commonEnable": "Enable",
    "commonDisable": "Disable",
    "commonOk": "OK",
    "commonKeep": "Keep",
    "commonDiscard": "Discard",
    "commonContinue": "Continue",
    "commonIncome": "Income",
    "commonSpending": "Spending",
    "commonNet": "Net",
    "commonUnavailable": "Unavailable",
    "commonSignOut": "Sign out",
    "commonEdit": "Edit",
    "commonImport": "Import",
    "commonLoading": "Loading",
    "commonRemove": "Remove",
    "commonConfirm": "Confirm",
    "commonDismiss": "Dismiss",
    "commonToday": "Today",
    "commonThisWeek": "This week",
    "commonThisMonth": "This month",
    "commonAll": "All",
    "commonCustom": "Custom",
    "commonActive": "Active",
    "commonTitle": "Title",
    "commonName": "Name",
    "commonDescription": "Description",
    "commonStatus": "Status",
    "commonPriority": "Priority",
    "commonImportance": "Importance",
    "commonSummary": "Summary",
    "commonNotes": "Notes",
    "commonType": "Type",
    "commonLow": "Low",
    "commonNormal": "Normal",
    "commonMedium": "Medium",
    "commonHigh": "High",
    "commonNotSet": "Not set",
    "commonDueDate": "Due date",
    "commonAccount": "Account",
    "commonUnknown": "Unknown",
    "commonExpense": "Expense",
    "commonTransfer": "Transfer",
    "commonRefund": "Refund",
    "commonAdjustment": "Adjustment",
    "commonCreditCardPayment": "Credit card payment",
    "commonChecking": "Checking",
    "commonSavings": "Savings",
    "commonCard": "Card",
    "commonBuiltIn": "Built-in",
    "commonHidden": "Hidden",
    "commonVisible": "Visible",
    "commonDisabled": "Disabled",
    "commonCategories": "Categories",
    "commonRules": "Rules",
    "commonHistory": "History",
    "commonPeople": "People",
    "commonPreferences": "Preferences",
    "commonPerson": "Person",
    "commonPlan": "Plan",
    "commonCommitment": "Commitment",
    "commonRule": "Rule",
    "commonMemory": "Memory",
    "commonConversation": "Conversation",
    "commonUndated": "Undated",
    "commonYesterday": "Yesterday",
    "commonOlder": "Older",
    "commonUpcoming": "Upcoming",
    "commonInactive": "Inactive",
    "commonAttachment": "Attachment",
    "commonStart": "Start",
    "commonEnd": "End",
    "commonLeft": "Left",
    "commonOver": "Over",
    "commonSpent": "Spent",
    "commonBudgeted": "Budgeted",
    "commonMonthly": "Monthly",
    "commonWeekly": "Weekly",
    "commonOnTrack": "{onTrack}/{budgeted} on track",
    "commonTransactionCount": "{count} transactions",
    "commonTransactionCountOne": "1 transaction",
    "commonRecordsApplied": "Applied to {count, plural, one{1 record} other{{count} records}}.",
    "commonAiCalls": "{count} AI calls",
    "commonAiCallsThisMonth": "{count} AI calls this month",
    "commonMinutesFormat": "{minutes} min",
    "commonMinutesUnderOne": "<1 min",
    "commonAddedDate": "Added {date}",
    "commonUpdatedDate": "Updated {date}",
    "commonDueDateValue": "Due {date}",
    "commonTargetDateValue": "Target {date}",
    "commonLabeledValue": "{label}: {value}",
    "commonAcrossAccounts": "Across {accountCount} connected account{accountCountSuffix}",
    "commonConnectedAccountCount": "{count} connected account{countSuffix}",
    "commonCopiedLabel": "{label} copied.",
    "commonArchivedNamed": "{label} archived",
    "commonCommaSeparated": "Comma-separated",
    "commonAmountHintDash": "—",
    "commonMonthYear": "{month} {year}",
    "commonMonthJanuary": "January",
    "commonMonthFebruary": "February",
    "commonMonthMarch": "March",
    "commonMonthApril": "April",
    "commonMonthMay": "May",
    "commonMonthJune": "June",
    "commonMonthJuly": "July",
    "commonMonthAugust": "August",
    "commonMonthSeptember": "September",
    "commonMonthOctober": "October",
    "commonMonthNovember": "November",
    "commonMonthDecember": "December",
    "commonMonthShortJan": "Jan",
    "commonMonthShortFeb": "Feb",
    "commonMonthShortMar": "Mar",
    "commonMonthShortApr": "Apr",
    "commonMonthShortMay": "May",
    "commonMonthShortJun": "Jun",
    "commonMonthShortJul": "Jul",
    "commonMonthShortAug": "Aug",
    "commonMonthShortSep": "Sep",
    "commonMonthShortOct": "Oct",
    "commonMonthShortNov": "Nov",
    "commonMonthShortDec": "Dec",
    "commonMonthShortOld": "Old",
    # Boot & onboarding
    "bootErrorTitle": "Clarity could not start",
    "bootErrorTryAgain": "Try again",
    "bootErrorFallbackMessage": "Check your connection and try again.",
    "onboardingWelcomeTitle": "Welcome to Clarity",
    "onboardingSubtitle": "Name your Clarity space. Next, you can connect your bank or use CSV as a manual fallback.",
    "onboardingNameLabel": "Your name",
    "onboardingNameHint": "Pedro",
    # Profile (remaining)
    "profileScreenTitle": "Profile",
    "profileEditNameTitle": "Edit profile name",
    "profileUpdatedSnackBar": "Profile updated.",
    "profileUpdateFailed": "Could not update profile.",
    "profileSignOutTitle": "Sign out?",
    "profileSignOutBody": "You can sign back in when you are ready.",
    "profileDefaultUserName": "Clarity user",
    "profileAccountSection": "Account",
    "profileNameTitle": "Profile name",
    "profileAddYourName": "Add your name",
    "profileMfaTitle": "Multi-factor authentication",
    "profileMfaSubtitle": "Authenticator app setup and security options",
    "profileRexVoiceSection": "Rex and voice",
    "profileVoiceUsageTitle": "Voice usage",
    "profileVoiceUsageSubtitle": "Minutes today, this week, and this month",
    "profileSessionSection": "Session",
    "profileSignOutSubtitle": "Leave this device signed out of Clarity",
    "profileHeaderLabel": "Clarity profile",
    # Usage summary
    "usageSummaryTitle": "Voice usage",
    "usageSummaryLoading": "Loading usage",
    "usageSummaryDailyVoiceMinutes": "Daily voice minutes",
    "usageSummaryDailyAiCalls": "Daily AI calls",
    "usageSummaryHeaderLabel": "Rex voice activity",
    # Shell / Plaid snackbars
    "homeShellBankConnectedSuccess": "Bank connected successfully: {institutionName}{accountsSyncedSuffix}.",
    "homeShellBankConnectedYourBank": "your bank",
    "homeShellBankConnectedAccountsSynced": " and synced {count, plural, one{1 account} other{{count} accounts}}",
    "homeShellBankConnectionStoppedWithCode": "Bank connection stopped before it finished. You can try again. ({errorCode})",
    "homeShellBankConnectionStoppedWithStatus": "Bank connection stopped before it finished. Plaid status: {status}.",
    "homeShellBankConnectionCancelled": "Bank connection cancelled. No account was added.",
    "homeShellBankConnectionOpenFailed": "Could not open bank connection.",
    # Dashboard overview
    "dashboardOverviewTitle": "Overview",
    "dashboardOverviewImportCsvTooltip": "Import CSV instead",
    "dashboardOverviewDeleteCsvUploadTooltip": "Delete CSV upload",
    "dashboardOverviewDeleteAccountTooltip": "Delete account",
    "dashboardOverviewMonthlyCashFlow": "Monthly cash flow",
    "dashboardOverviewSpendingByCategory": "Spending by category",
    "dashboardOverviewIncomeVsSpending": "Income vs spending",
    "dashboardOverviewSixMonthTrend": "Six-month spend trend",
    "dashboardOverviewSpendingPressure": "Spending pressure",
    "dashboardOverviewBudgetPerformance": "Budget performance",
    "dashboardOverviewAccountHealth": "Account health",
    "dashboardOverviewDataLoadBannerTitle": "Some financial data could not load",
    "dashboardOverviewDataLoadBannerBody": "Clarity is showing the available records, but {sourceLabel} may be incomplete. Rex will treat finance answers as degraded until this refreshes.",
    "dashboardOverviewDataLoadBannerFallbackSource": "financial data",
    "dashboardOverviewLoadingLabel": "Loading your financial data...",
    "dashboardEmptyConnectFirstBankTitle": "Connect your first bank",
    "dashboardEmptyConnectFirstBankBody": "Clarity works best with connected accounts, so balances and transactions stay current automatically.",
    "dashboardResolvingTitle": "Resolving imported transactions",
    "dashboardResolvingBody": "Your statement is connected, but the transaction rows are still loading. Values will appear when the read model is complete.",
    "dashboardOverviewTotalBalance": "Total balance",
    "dashboardOverviewAccountBalance": "Account balance",
    "dashboardOverviewFromConnectedAccounts": "From your connected accounts",
    "dashboardOverviewThisMonthLabel": "This month",
    "dashboardOverviewActivityNotBalanceNote": "Activity this month — not the same as balance",
    "dashboardTransactionsSectionTitle": "Transactions",
    "dashboardTransactionsClearFilters": "Clear",
    "dashboardTransactionsLoadingLabel": "Loading transactions",
    "dashboardTransactionsLoadError": "Could not load transactions.",
    "dashboardTransactionsNoImportedHistory": "No imported history",
    "dashboardTransactionsModeMonths": "Months",
    "dashboardTransactionsModeCategories": "Categories",
    "dashboardTransactionsSearchHint": "Search merchant, category, month, or amount",
    "dashboardTransactionsFilterCategory": "Category",
    "dashboardTransactionsFilterAllCategories": "All categories",
    "dashboardTransactionsFilterAccount": "Account",
    "dashboardTransactionsFilterAllAccounts": "All accounts",
    "dashboardTransactionsTimeFilterAllHistory": "All history",
    "dashboardTransactionsTimeFilterDashboardMonth": "Dashboard month",
    "dashboardTransactionsTimeFilterLatestTxMonth": "Latest tx month",
    "dashboardTransactionsTimeFilterLatestTxYear": "Latest tx year",
    "dashboardTransactionsSortNewest": "Newest",
    "dashboardTransactionsSortOldest": "Oldest",
    "dashboardTransactionsSortLargest": "Largest",
    "dashboardTransactionsSortMerchant": "Merchant A-Z",
    "dashboardTransactionsNoCategoriesMatch": "No categories match.",
    "dashboardTransactionsNoMonthsAfterFilter": "No months to show after filtering this file.",
    "dashboardTransactionsNetLabel": "net",
    "dashboardTransactionsHistoryRange": "History: {dateRange}",
    "dashboardTransactionsDashboardMonthRange": "Dashboard month: {dateRange}",
    "dashboardTransactionsLatestTxMonthRange": "Latest transaction month: {dateRange}",
    "dashboardTransactionsLatestTxYearRange": "Latest transaction year: {dateRange}",
    "dashboardTransactionsTapMonthHint": "Tap a month to inspect transactions | {dateRangeDescription}",
    "dashboardTransactionsFilteredCount": "{filtered} of {total} transactions | {dateRangeDescription}",
    # Accounts
    "accountsScreenRefreshTooltip": "Refresh accounts",
    "accountsScreenAddAccountTooltip": "Add account",
    "accountsScreenLoadError": "Could not load accounts.",
    "accountsScreenLoadingLabel": "Loading accounts",
    "accountsSummaryTotalBalance": "Total balance",
    "accountsEmptyTitle": "Connect your accounts",
    "accountsEmptyBody": "Start with connected bank accounts so Clarity can keep balances and transactions current.",
    "connectBankCardConnectButton": "Connect Bank",
    "connectBankCardImportCsvButton": "Import CSV instead",
    "connectBankCardAddManualButton": "Add manual account",
    "accountsNoticeDismissTooltip": "Dismiss",
    "accountTileThisMonthNet": "This month {amount} net",
    "accountTileViewAccount": "View account",
    "plaidAccountAvailableLabel": "Available",
    "plaidAccountThisMonthLabel": "This month",
    "plaidAccountInOutSummary": "{income} in / {spending} out",
    "plaidAccountLastSyncedUnavailable": "Last synced unavailable",
    "plaidAccountLastSyncedJustNow": "Last synced just now",
    "plaidAccountLastSyncedMinutesAgo": "Last synced {minutes}m ago",
    "plaidAccountLastSyncedHoursAgo": "Last synced {hours}h ago",
    "plaidAccountLastSyncedDate": "Last synced {date}",
    "plaidAccountResyncTooltipSyncing": "Syncing",
    "plaidAccountResyncTooltipLoginRequired": "Login required",
    "plaidAccountResyncTooltipExpiringSoon": "Expiring soon",
    "plaidAccountResyncTooltipDisconnected": "Disconnected",
    "plaidAccountResyncTooltipDefault": "Resync",
    "plaidAccountDisconnectTooltip": "Disconnect bank",
    "addAccountDialogTitle": "New account",
    "addAccountDialogInstitutionLabel": "Institution (optional)",
    "addAccountDialogTypeLabel": "Type",
    "addAccountDialogBalanceLabel": "Current balance (optional)",
    "addAccountDialogInvalidBalance": "Enter a valid balance or leave it blank.",
    "accountsSheetAddAccountTitle": "Add account",
    "accountsSheetAddAccountSubtitle": "Connect another bank with Plaid, or use manual tools when you need a fallback.",
    "accountsSheetConnectBankTitle": "Connect bank",
    "accountsSheetConnectBankSubtitle": "Use Plaid to add another bank.",
    "accountsSheetImportCsvTitle": "Import CSV instead",
    "accountsSheetImportCsvSubtitle": "Create a manual account for bank files.",
    "accountsSheetAddManualTitle": "Add manual account",
    "accountsSheetAddManualSubtitle": "Track an account without Plaid.",
    "accountsScreenDisconnectTitle": "Disconnect bank?",
    "accountsScreenDisconnectContent": "Disconnect {accountName}? This stops future Plaid sync for this bank. Existing history stays in Clarity.",
    "accountsScreenDisconnectButton": "Disconnect bank",
    "accountsScreenBankDisconnectedSnack": "Bank disconnected.",
    "accountsNavigationCouldNotSaveAccount": "Could not save account.",
    "csvPlaidWarningTitle": "Import CSV into connected account?",
    "csvPlaidWarningContent": "{accountName} already syncs through Plaid. Importing a CSV here can add duplicate rows if the file overlaps with synced transactions.",
    "csvPlaidWarningContinue": "Continue import",
    "accountSelectionAppBarTitle": "Import CSV instead",
    "accountSelectionPreviewingCsv": "Previewing CSV...",
    "accountSelectionCouldNotImport": "Could not import this file.",
    "accountSelectionEmptyTitle": "Add a manual account for this CSV",
    "accountSelectionAddManualButton": "Add manual account",
    "accountSelectionInstructions": "CSV import is manual. Choose the account this file belongs to; connected bank accounts update automatically.",
    "accountSelectionCsvMayDuplicate": "CSV may duplicate synced rows",
    "csvPreviewDialogTitle": "CSV import preview",
    "csvPreviewDialogDateRange": "Date range",
    "csvPreviewDialogRowsFound": "Rows found",
    "csvPreviewDialogNewRows": "New rows",
    "csvPreviewDialogDuplicates": "Duplicates",
    "csvPreviewDialogSpendingRows": "Spending rows",
    "csvPreviewDialogIncomeRows": "Income rows",
    "csvPreviewDialogEndingBalance": "Ending balance",
    "csvPreviewDialogNoNewRows": "No new rows",
    "accountDetailFallbackTitle": "Account",
    "accountDetailLoadingLabel": "Loading account",
    "accountDetailLoadError": "Could not load account.",
    "accountDetailDeletingCsvProgress": "Deleting CSV upload...",
    "accountDetailDeleteCsvUploadTitle": "Delete CSV upload",
    "accountDetailConfirmDeleteCsvTitle": "Delete this CSV upload?",
    "accountDetailDeleteUploadButton": "Delete upload",
    "accountDetailDeleteAccountTitle": "Delete account?",
    "accountDetailDeleteAccountContent": "Delete this account and all its transactions? This cannot be undone.",
    "accountDetailDeleteAccountButton": "Delete account",
    "accountDetailKeepCategories": "Keep",
    "accountDetailDeleteCategories": "Delete",
    # Chat / Rex
    "chatPageDefaultTitle": "Rex",
    "chatPageSendingImage": "Sending image…",
    "chatPageSendFailed": "Could not send message.",
    "chatPageReadFileFailed": "Could not read selected file.",
    "chatPageStartVoiceFailed": "Could not start Rex.",
    "chatPageShowVoiceCallTooltip": "Show voice call",
    "chatPageCallRexTooltip": "Call Rex",
    "chatInputAttachTooltip": "Attach file or image",
    "chatInputStartVoiceModeTooltip": "Start voice mode",
    "chatInputMessageHint": "Message Assistant…",
    "chatInputSendTooltip": "Send",
    "chatInputRemoveAttachmentTooltip": "Remove attachment",
    "attachmentSheetTitle": "Attach",
    "attachmentSheetGalleryTitle": "Gallery",
    "attachmentSheetGallerySubtitle": "Choose an image from photos.",
    "attachmentSheetCameraTitle": "Camera",
    "attachmentSheetCameraSubtitle": "Take a new photo.",
    "attachmentSheetFilesTitle": "Files",
    "attachmentSheetFilesSubtitle": "Choose PDF, text, CSV, markdown, or image files.",
    "chatTranscriptWelcomeMessage": "I'm Rex. Tell me what's happening, what changed, or what you want me to remember.",
    "chatTranscriptReadyTitle": "Rex is ready",
    "chatTranscriptPromptRemember": "What should I remember?",
    "chatTranscriptPromptThinkTonight": "Help me think through tonight.",
    "chatTranscriptPromptCheckKnows": "Check what Clarity knows.",
    "chatBubbleClarityAction": "Clarity action",
    "voicePanelStartTalking": "Start talking",
    "voicePanelProcessing": "Processing…",
    "voicePanelMuted": "Muted",
    "voicePanelSettingsTooltip": "Settings",
    "voicePanelTryAgainTooltip": "Try again",
    "voicePanelUnmuteMicTooltip": "Unmute mic",
    "voicePanelMuteMicTooltip": "Mute mic",
    "voicePanelEndVoiceTooltip": "End voice",
    "conversationListTitle": "Chats",
    "conversationListDeleteTitle": "Delete conversation?",
    "conversationListDeleteBody": "This removes the conversation and its messages.",
    "conversationListDeleteFailed": "Could not delete conversation.",
    "conversationListDeletedSnackBar": "Conversation deleted",
    "conversationListNewConversationTooltip": "New conversation",
    "conversationListLoading": "Loading chats",
    "conversationListEmptyTitle": "No chats yet",
    "conversationListEmptyMessage": "Start a fresh conversation when you are ready.",
    "conversationListSearchHint": "Search chats",
    "conversationListClearSearchTooltip": "Clear search",
    "conversationListSearching": "Searching chats",
    "conversationListNoMatchesTitle": "No matching chats",
    "conversationListNewChat": "New chat",
    "conversationHistoryNewConversation": "New conversation",
    "conversationHistoryMatchedConversation": "Matched conversation",
    "conversationHistoryNoMessagesYet": "No messages yet",
    "conversationHistoryActionsTooltip": "Conversation actions",
    # Memory
    "memoryPageTitle": "What Clarity Knows",
    "memoryPageRefreshTooltip": "Refresh information",
    "memoryPageMemoryUpdated": "Memory updated",
    "memoryPageMemoryArchived": "Memory archived",
    "memoryPageActionFailed": "Memory action failed.",
    "memoryHeaderSearchHint": "Search what Clarity knows",
    "memoryHeaderClearSearchTooltip": "Clear search",
    "memoryHeaderSectionTitle": "What Clarity knows",
    "memoryHeaderActiveOnly": "Active information only",
    "memoryHeaderLoading": "Loading memory",
    "memoryHeaderEmptyActiveTitle": "Clarity is still learning",
    "memoryHeaderEmptyTitle": "No saved information yet",
    "memoryArchiveTitle": "Archive saved information?",
    "memoryArchiveBody": "This saved information will stop being used in future conversations. It will remain in information history.",
    "memoryTileActionsTooltip": "Memory actions",
    "memoryTileQuickEdit": "Quick edit",
    "memoryEditEditMemoryTitle": "Edit memory",
    "memoryEditSummaryHint": "What Clarity should remember",
    # Goals / accountability
    "accountabilityPageTitle": "Goals",
    "accountabilityPageRefreshTooltip": "Refresh goals",
    "accountabilitySharedAddGoal": "Add goal",
    "accountabilitySharedAddOpenThread": "Add open thread",
    "accountabilitySharedLoading": "Loading goals",
    "accountabilitySharedEmptyTitle": "No goals yet",
    "accountabilitySharedEmptyBody": "Start with one simple goal or tell Rex in chat.",
    "accountabilitySharedAddFirstGoal": "Add your first goal",
    "accountabilitySectionsActiveGoals": "Active Goals",
    "accountabilitySectionsNoActiveGoals": "No active goals yet.",
    "accountabilitySectionsOpenThreads": "Open Threads",
    "accountabilitySectionsNoOpenThreads": "No open threads yet.",
    "accountabilityTilesGoalActionsTooltip": "Goal actions",
    "accountabilityTilesOpenThreadActionsTooltip": "Open thread actions",
    "accountabilityTilesMarkMissed": "Mark missed",
    "accountabilityDetailGoalDetails": "Goal details",
    "accountabilityDetailEditOpenThread": "Edit open thread",
    "accountabilityDetailNotesHint": "Why this matters",
    # Budgets
    "budgetsScreenManageCategoriesTooltip": "Manage categories",
    "budgetsScreenSaveChangesTooltip": "Save changes",
    "budgetsScreenLoadError": "Could not load budgets.",
    "budgetsScreenLoadingLabel": "Loading budgets",
    "budgetsScreenBudgetVsSpentTitle": "Budget vs spent",
    "budgetsHeaderSelectMonth": "Select month",
    "budgetsHeaderPickWeekStart": "Pick week start",
    "budgetsHeaderNoMonthsAvailable": "No months available.",
    "budgetsScreenUnsavedChangesTitle": "Save changes before switching period?",
    "budgetsScreenUnsavedChangesContent": "You have unsaved budget changes for this period.",
    "budgetsScreenSaveFailedSnack": "Could not save budgets. Try again.",
    "budgetCategoryListTitle": "Categories",
    "budgetCategoryListEmpty": "No active budget categories yet.",
    "budgetCategoryRowStatusNoBudget": "Spent {spent} · No budget",
    "budgetCategoryRowStatusOver": "Spent {spent} · Over {amount}",
    "budgetCategoryRowStatusLeft": "Spent {spent} · Left {amount}",
    "categorySheetHeaderTitle": "Manage categories",
    "categorySheetAddCustomCategory": "Add custom category",
    "categorySheetSavedCategoriesLabel": "Saved categories",
    "categorySheetNoSavedCategories": "No saved categories yet.",
    "categorySheetMerchantRulesLabel": "Merchant rules",
    "categorySheetNoMerchantRules": "No learned merchant rules yet.",
    "categorySheetRecentChangesLabel": "Recent changes",
    "categorySheetNoAuditEvents": "No financial changes recorded yet.",
    "categoryDialogNameLabel": "Category name",
    "categorySheetAddCategoryTitle": "Add category",
    "categorySheetRenameCategoryTitle": "Rename category",
    "categorySheetDeleteCategoryTitle": "Delete category?",
    "categorySheetMergeCategoryTitle": "Merge category?",
    "categorySheetMergeButton": "Merge",
    "categorySheetCategoryInUseTitle": "Category is in use",
    "categorySheetClose": "Close",
    "transactionCategoryNoCategories": "No categories",
    "transactionCategoryNewCategoryHint": "New category",
    "transactionCategoryOnlyThisOne": "Only this one",
    "transactionCategoryUpdatedSnack": "Category updated.",
    # MFA
    "mfaEnrollmentAppBarTitle": "Multi-factor authentication",
    "mfaEnrollmentTurnOffTitle": "Turn off MFA?",
    "mfaEnrollmentCancel": "Cancel",
    "mfaEnrollmentTurnOff": "Turn off",
    "mfaEnrollmentAuthenticatorApps": "Authenticator apps",
    "mfaEnrollmentMfaOn": "MFA is on",
    "mfaEnrollmentMfaOff": "MFA is off",
    "mfaEnrollmentTurnOnMfa": "Turn on MFA",
    "mfaEnrollmentSetupTitle": "Set up authenticator app",
    "mfaEnrollmentCodeLabel": "6-digit code",
    "mfaEnrollmentEnableMfa": "Enable MFA",
    "mfaVerificationTitle": "Enter your MFA code",
    "mfaVerificationVerifyAndContinue": "Verify and continue",
}

PLACEHOLDER_META: dict[str, dict] = {
    "commonOnTrack": {"placeholders": {"onTrack": {"type": "int"}, "budgeted": {"type": "int"}}},
    "commonTransactionCount": {"placeholders": {"count": {"type": "int"}}},
    "commonRecordsApplied": {"placeholders": {"count": {"type": "int"}}},
    "commonAiCalls": {"placeholders": {"count": {"type": "int"}}},
    "commonAiCallsThisMonth": {"placeholders": {"count": {"type": "int"}}},
    "commonMinutesFormat": {"placeholders": {"minutes": {"type": "String"}}},
    "commonAddedDate": {"placeholders": {"date": {"type": "String"}}},
    "commonUpdatedDate": {"placeholders": {"date": {"type": "String"}}},
    "commonDueDateValue": {"placeholders": {"date": {"type": "String"}}},
    "commonTargetDateValue": {"placeholders": {"date": {"type": "String"}}},
    "commonLabeledValue": {"placeholders": {"label": {"type": "String"}, "value": {"type": "String"}}},
    "commonAcrossAccounts": {"placeholders": {"accountCount": {"type": "int"}, "accountCountSuffix": {"type": "String"}}},
    "commonConnectedAccountCount": {"placeholders": {"count": {"type": "int"}, "countSuffix": {"type": "String"}}},
    "commonCopiedLabel": {"placeholders": {"label": {"type": "String"}}},
    "commonArchivedNamed": {"placeholders": {"label": {"type": "String"}}},
    "commonMonthYear": {"placeholders": {"month": {"type": "String"}, "year": {"type": "String"}}},
    "homeShellBankConnectedSuccess": {"placeholders": {"institutionName": {"type": "String"}, "accountsSyncedSuffix": {"type": "String"}}},
    "homeShellBankConnectedAccountsSynced": {"placeholders": {"count": {"type": "int"}}},
    "homeShellBankConnectionStoppedWithCode": {"placeholders": {"errorCode": {"type": "String"}}},
    "homeShellBankConnectionStoppedWithStatus": {"placeholders": {"status": {"type": "String"}}},
    "dashboardOverviewDataLoadBannerBody": {"placeholders": {"sourceLabel": {"type": "String"}}},
    "dashboardTransactionsHistoryRange": {"placeholders": {"dateRange": {"type": "String"}}},
    "dashboardTransactionsDashboardMonthRange": {"placeholders": {"dateRange": {"type": "String"}}},
    "dashboardTransactionsLatestTxMonthRange": {"placeholders": {"dateRange": {"type": "String"}}},
    "dashboardTransactionsLatestTxYearRange": {"placeholders": {"dateRange": {"type": "String"}}},
    "dashboardTransactionsTapMonthHint": {"placeholders": {"dateRangeDescription": {"type": "String"}}},
    "dashboardTransactionsFilteredCount": {"placeholders": {"filtered": {"type": "int"}, "total": {"type": "int"}, "dateRangeDescription": {"type": "String"}}},
    "accountTileThisMonthNet": {"placeholders": {"amount": {"type": "String"}}},
    "plaidAccountInOutSummary": {"placeholders": {"income": {"type": "String"}, "spending": {"type": "String"}}},
    "plaidAccountLastSyncedMinutesAgo": {"placeholders": {"minutes": {"type": "int"}}},
    "plaidAccountLastSyncedHoursAgo": {"placeholders": {"hours": {"type": "int"}}},
    "plaidAccountLastSyncedDate": {"placeholders": {"date": {"type": "String"}}},
    "accountsScreenDisconnectContent": {"placeholders": {"accountName": {"type": "String"}}},
    "csvPlaidWarningContent": {"placeholders": {"accountName": {"type": "String"}}},
    "budgetCategoryRowStatusNoBudget": {"placeholders": {"spent": {"type": "String"}}},
    "budgetCategoryRowStatusOver": {"placeholders": {"spent": {"type": "String"}, "amount": {"type": "String"}}},
    "budgetCategoryRowStatusLeft": {"placeholders": {"spent": {"type": "String"}, "amount": {"type": "String"}}},
}


def load_arb(path: Path) -> dict:
    with path.open(encoding="utf-8") as f:
        return json.load(f)


def save_arb(path: Path, data: dict) -> None:
    with path.open("w", encoding="utf-8", newline="\n") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write("\n")


def merge_s2(base: dict, strings: dict[str, str]) -> dict:
    out = dict(base)
    for key, value in strings.items():
        if key.startswith("@"):
            continue
        out[key] = value
        meta_key = f"@{key}"
        if key in PLACEHOLDER_META:
            out[meta_key] = {"placeholders": PLACEHOLDER_META[key]["placeholders"]}
    return out


def main() -> None:
    en = load_arb(EN_PATH)
    merged = merge_s2(en, S2_STRINGS)
    save_arb(EN_PATH, merged)

    es = {k: v for k, v in merged.items() if not k.startswith("@") and k not in ("@@locale", "@@context")}
    es_out: dict = {"@@locale": "es"}
    for key in sorted(es.keys()):
        if key in merged:
            es_out[key] = merged[key]
            meta = f"@{key}"
            if meta in merged:
                es_out[meta] = merged[meta]
    save_arb(ES_PATH, es_out)
    print(f"Merged {len(S2_STRINGS)} S2 keys into {EN_PATH.name}")


if __name__ == "__main__":
    main()
