STOP_WORDS = {
    "about",
    "after",
    "again",
    "also",
    "and",
    "are",
    "because",
    "but",
    "can",
    "could",
    "for",
    "from",
    "have",
    "how",
    "into",
    "just",
    "like",
    "more",
    "need",
    "not",
    "now",
    "should",
    "that",
    "the",
    "this",
    "what",
    "when",
    "where",
    "with",
    "would",
    "you",
    "your",
}

CONCEPT_GROUPS = {
    "birthday": {
        "anniversary",
        "birthdate",
        "birthday",
        "birthdays",
        "date",
        "dates",
    },
    "family": {
        "brother",
        "dad",
        "father",
        "family",
        "mom",
        "mother",
        "mum",
        "parent",
        "parents",
        "sister",
    },
    "important_date": {
        "anniversary",
        "birthday",
        "calendar",
        "date",
        "dates",
        "day",
        "event",
        "important",
    },
    "profile": {
        "birthday",
        "fact",
        "facts",
        "identity",
        "important",
        "location",
        "name",
        "preference",
        "profile",
        "timezone",
    },
    "work": {"career", "job", "manager", "office", "salary", "work", "workplace"},
    "money": {"bill", "budget", "debt", "finance", "money", "rent", "savings"},
    "location": {
        "address",
        "area",
        "city",
        "eastern",
        "edt",
        "est",
        "home",
        "house",
        "live",
        "lives",
        "living",
        "location",
        "massachusetts",
        "place",
        "state",
        "timezone",
    },
    "relationship": {
        "date",
        "dating",
        "girl",
        "girlfriend",
        "monday",
        "name",
        "offday",
        "person",
        "restaurant",
        "relationship",
        "wife",
    },
    "time": {
        "birthday",
        "calendar",
        "clock",
        "date",
        "day",
        "eastern",
        "edt",
        "est",
        "morning",
        "night",
        "schedule",
        "time",
        "timezone",
        "today",
        "tomorrow",
        "tonight",
        "week",
    },
    "immigration": {"ead", "green", "immigration", "status", "uscis", "visa"},
    "stress": {
        "anxiety",
        "burnout",
        "frustrated",
        "pressure",
        "stress",
        "stressed",
    },
}

PROFILE_CONTEXT_TERMS = {
    "birthday",
    "family",
    "identity",
    "important",
    "important_date",
    "profile",
    "fact",
}
