DEEP_TERMS = (
    "deep think",
    "think deeply",
    "go deeper",
    "full analysis",
    "analyze thoroughly",
    "reason through",
    "break this down",
)

MEMORY_UPDATE_TERMS = (
    "actually",
    "correct that",
    "correction",
    "change that",
    "update that",
    "replace",
    "no, it's",
    "no it's",
    "not the",
    "not my",
    "not his",
    "not her",
    "it's not",
    "it is not",
    "with one m",
    "with two m",
    "spelled",
)

MEMORY_SAVE_TERMS = (
    "remember",
    "save this",
    "keep that in memory",
    "keep this in memory",
    "my name is",
    "i live in",
    "i work at",
    "my birthday is",
    "birthday is",
    "i prefer",
    "i like",
    "i hate",
)

MEMORY_STORE_TERMS = (
    "chat",
    "chats",
    "conversation",
    "conversations",
    "memory",
    "memories",
    "mention",
    "mentioned",
    "remember",
    "said",
    "saved",
    "say",
    "talked",
    "told you",
)

RECALL_BEFORE_UPDATE_TERMS = (
    "chat",
    "chats",
    "conversation",
    "conversations",
    "do you remember",
    "find",
    "mention",
    "mentioned",
    "said",
    "search",
    "talked",
    "told",
    "what did i say",
)

MEMORY_DELETE_TERMS = (
    "archive",
    "clear",
    "delete",
    "erase",
    "forget",
    "get rid of",
    "remove",
)

GOAL_TERMS = (
    "accountability",
    "behind",
    "commitment",
    "commitments",
    "deadline",
    "deadlines",
    "goal",
    "goals",
    "milestone",
    "milestones",
    "my plan",
    "my plans",
    "on track",
    "progress",
    "target",
    "targets",
    "remind me",
    "reminder",
    "send $",
    "send her $",
    "send him $",
    "doordash",
    "uber eats",
    "again",
)

ACCOUNTABILITY_STRUCTURED_TERMS = (
    "accountability",
    "again",
    "behind",
    "commitment",
    "commitments",
    "deadline",
    "deadlines",
    "doordash",
    "missed",
    "overdue",
    "rule",
    "rules",
    "uber eats",
)

FINANCE_TERMS = (
    "account balance",
    "available balance",
    "bank account",
    "bank accounts",
    "bank balance",
    "budget",
    "budgeting",
    "cash flow",
    "checking account",
    "checking accounts",
    "credit card",
    "debit card",
    "debt",
    "expense",
    "expenses",
    "finance",
    "financial",
    "income",
    "merchant",
    "merchants",
    "plaid",
    "savings account",
    "savings accounts",
    "spend",
    "spent",
    "spending",
    "subscription",
    "subscriptions",
    "transaction",
    "transactions",
)

CASUAL_EXACT = {
    "hey",
    "hi",
    "hello",
    "hello rex",
    "hey rex",
    "good morning",
    "good afternoon",
    "good evening",
    "thanks",
    "thank you",
    "thank you rex",
    "ok",
    "okay",
}

CASUAL_TERMS = (
    "how are you",
    "how's your day",
    "how is your day",
    "how's your night",
    "how is your night",
    "what's up",
)


def contains(normalized_message: str, terms: tuple[str, ...]) -> bool:
    return any(term in normalized_message for term in terms)
