[pytest]
filterwarnings =
    ignore:You are using a Python version 3\.9 past its end of life\..*:FutureWarning:google.auth
    ignore:You are using a Python version 3\.9 past its end of life\..*:FutureWarning:google.oauth2
    ignore:urllib3 v2 only supports OpenSSL.*
